FROM ubuntu:noble

# Switch to apt noninteractive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y locales tzdata && apt clean -y && rm -rf /var/lib/apt/lists/* \
    && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen en_US.UTF-8 \
    && update-locale LANG=en_US.UTF-8 \
    && ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime \
    && echo "America/Los_Angeles" > /etc/timezone
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# General development tools
RUN apt update && apt install -y \
	bash-completion \
	curl \
	gcc \
	git \
	gpg \
	htop \
	iftop \
	jq \
	less \
	lsof \
	make \
	man \
	ncdu \
	neovim \
	net-tools \
	procps \
	rsync \
	screen \
	slurm \
	sudo \
	tmux \
	tree \
	unzip \
	uuid \
	vim \
	wget \
	yq \
	zip \
	&& apt autoremove --purge -y \
	&& apt clean -y && rm -rf /var/lib/apt/lists/*

# Add vscode user (devcontainer default UID)
RUN groupadd -r vscode \
	&& useradd -rs /bin/bash -m -g vscode -u 1001 vscode \
	&& echo "vscode:vscode" | chpasswd \
	&& echo "vscode ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vscode

# Add agent user
RUN groupadd -r agent \
	&& useradd -rs /bin/bash -m -g agent agent \
	&& echo "agent:agent" | chpasswd \
	&& echo "agent ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/agent

# Install Cursor, Claude, and Copilot agents
ENV CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1
USER agent
RUN curl -fsSL https://cursor.com/install | bash
RUN curl -fsSL https://claude.ai/install.sh | bash
RUN curl -fsSL https://gh.io/copilot-install | bash
USER root

# GitHub CLI
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list \
	&& apt update && apt install -y gh \
	&& apt clean && rm -rf /var/lib/apt/lists/*

# Node.js
RUN NODE_MAJOR=24 \
	&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
	&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
	&& apt update && apt install -y nodejs \
	&& npm install -g npm@latest \
	&& npm config set -g update-notifier false \
	&& corepack enable \
	&& corepack prepare yarn@stable --activate \
	&& rm -f /etc/apt/sources.list.d/nodesource.list /etc/apt/keyrings/nodesource.gpg \
	&& apt clean && rm -rf /var/lib/apt/lists/*

# Bun
USER agent
RUN curl -fsSL https://bun.sh/install | bash
USER root

COPY --chmod=755 finalize /finalize
COPY --chmod=755 post-create-base.sh /var/post-create-base.sh
COPY --chmod=755 post-start-base.sh /var/post-start-base.sh

COPY .bashrc-root /root/.bashrc
COPY .bashrc-user /home/vscode/.bashrc
COPY .bashrc-user /home/agent/.bashrc
