#!/bin/bash


# Configure gitconfig for agent user
cat > /home/agent/.gitconfig <<EOF
[commit]
	gpgSign = false
[safe]
	directory = /workspace
[init]
	defaultBranch = main
EOF
chmod 644 /home/agent/.gitconfig


# Fix absolute symlinks in agent home. Make them relative for portability
find /home/agent -type l | while read -r link; do
    target=$(readlink "$link")
    if [[ "$target" == /home/agent/* ]]; then
        home_rel="${target#/home/agent/}"
        link_dir=$(dirname "${link#/home/agent/}")
        if new_target=$(realpath -m --relative-to="/home/agent/$link_dir" "/home/agent/$home_rel"); then
            ln -sf "$new_target" "$link"
        fi
    fi
done


# Self-delete
rm -- "$0"
