name: Workflow Call - Build & Push

on:
  workflow_call:
    inputs:
      push:
        description: "Push the image to Docker Hub"
        type: boolean
        required: true
    outputs:
      pushed_new_image:
        description: "Whether a new image was pushed to the registry"
        value: ${{ jobs.build.outputs.pushed_image == 'true' }}

jobs:
  build:
    name: Build & Push (${{ matrix.variant }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [default, godot]
    outputs:
      pushed_image: ${{ steps.push-image.outputs.pushed }}
    env:
      DOCKERFILE: Dockerfile.${{ matrix.variant }}
      BUILD_TAG: build-image-${{ matrix.variant }}
      REPO_NAME: agent-${{ matrix.variant }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          file: ${{ env.DOCKERFILE }}
          tags: ${{ env.BUILD_TAG }}
          push: false
          load: true

      - name: Docker Push - Login and push
        id: push-image
        if: ${{ fromJSON(inputs.push) }}
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PAT_TOKEN }}"
          docker tag ${{ env.BUILD_TAG }} ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest
          echo "pushed=true" >> "$GITHUB_OUTPUT"
