name: Push (main)

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC

  push:
    branches:
      - main

jobs:
  build_base:
    name: Build Base
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
      packages: write
    with:
      variant: base
      push: true
      export_artifact: false

  build_variants:
    name: Build Variants
    needs: build_base
    strategy:
      matrix:
        variant: [godot]
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
      packages: write
    with:
      variant: ${{ matrix.variant }}
      push: true
