name: Pull Request (main)

on:
  pull_request:
    branches:
      - main

jobs:
  build_base:
    name: Build Base
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
    with:
      variant: default
      push: false
      export_artifact: true

  build_variants:
    name: Build Variants
    needs: build_base
    strategy:
      matrix:
        variant: [godot]
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
    with:
      variant: ${{ matrix.variant }}
      push: false
      base_artifact: build-image-default
