name: Pull Request (main)

on:
  pull_request:
    branches:
      - main

jobs:
  Build:
    strategy:
      matrix:
        variant: [default, godot]
    uses: ./.github/workflows/_build.yml
    secrets: inherit
    permissions:
      actions: read
      contents: read
    with:
      push: false
